# Correlates of War country code to subregion name

df$subregion_name[df$ccode == 700] <- "Southern Asia"
df$subregion_name[df$ccode == 339] <- "Southern Europe"
df$subregion_name[df$ccode == 615] <- "Northern Africa"
df$subregion_name[df$ccode == 232] <- "Southern Europe"
df$subregion_name[df$ccode == 540] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 58] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 160] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 371] <- "Western Asia"
df$subregion_name[df$ccode == 900] <- "Australia and New Zealand"
df$subregion_name[df$ccode == 305] <- "Western Europe"
df$subregion_name[df$ccode == 373] <- "Western Asia"
df$subregion_name[df$ccode == 31] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 692] <- "Western Asia"
df$subregion_name[df$ccode == 771] <- "Southern Asia"
df$subregion_name[df$ccode == 53] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 370] <- "Eastern Europe"
df$subregion_name[df$ccode == 211] <- "Western Europe"
df$subregion_name[df$ccode == 80] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 434] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 760] <- "Southern Asia"
df$subregion_name[df$ccode == 145] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 346] <- "Southern Europe"
df$subregion_name[df$ccode == 571] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 140] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 835] <- "South-eastern Asia"
df$subregion_name[df$ccode == 355] <- "Eastern Europe"
df$subregion_name[df$ccode == 439] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 516] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 811] <- "South-eastern Asia"
df$subregion_name[df$ccode == 471] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 20] <- "Northern America"
df$subregion_name[df$ccode == 402] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 482] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 483] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 155] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 710] <- "Eastern Asia"
df$subregion_name[df$ccode == 100] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 581] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 484] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 94] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 344] <- "Southern Europe"
df$subregion_name[df$ccode == 40] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 352] <- "Western Asia"
df$subregion_name[df$ccode == 316] <- "Eastern Europe"
df$subregion_name[df$ccode == 390] <- "Northern Europe"
df$subregion_name[df$ccode == 490] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 522] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 54] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 42] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 130] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 651] <- "Northern Africa"
df$subregion_name[df$ccode == 92] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 411] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 531] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 366] <- "Northern Europe"
df$subregion_name[df$ccode == 530] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 950] <- "Melanesia"
df$subregion_name[df$ccode == 375] <- "Northern Europe"
df$subregion_name[df$ccode == 220] <- "Western Europe"
df$subregion_name[df$ccode == 481] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 420] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 372] <- "Western Asia"
df$subregion_name[df$ccode == 255] <- "Western Europe"
df$subregion_name[df$ccode == 452] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 350] <- "Southern Europe"
df$subregion_name[df$ccode == 55] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 90] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 438] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 404] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 110] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 41] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 91] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 310] <- "Eastern Europe"
df$subregion_name[df$ccode == 395] <- "Northern Europe"
df$subregion_name[df$ccode == 750] <- "Southern Asia"
df$subregion_name[df$ccode == 850] <- "South-eastern Asia"
df$subregion_name[df$ccode == 630] <- "Southern Asia"
df$subregion_name[df$ccode == 645] <- "Western Asia"
df$subregion_name[df$ccode == 205] <- "Northern Europe"
df$subregion_name[df$ccode == 666] <- "Western Asia"
df$subregion_name[df$ccode == 325] <- "Southern Europe"
df$subregion_name[df$ccode == 437] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 51] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 740] <- "Eastern Asia"
df$subregion_name[df$ccode == 663] <- "Western Asia"
df$subregion_name[df$ccode == 705] <- "Central Asia"
df$subregion_name[df$ccode == 501] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 946] <- "Micronesia"
df$subregion_name[df$ccode == 690] <- "Western Asia"
df$subregion_name[df$ccode == 703] <- "Central Asia"
df$subregion_name[df$ccode == 812] <- "South-eastern Asia"
df$subregion_name[df$ccode == 367] <- "Northern Europe"
df$subregion_name[df$ccode == 660] <- "Western Asia"
df$subregion_name[df$ccode == 570] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 450] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 620] <- "Northern Africa"
df$subregion_name[df$ccode == 223] <- "Western Europe"
df$subregion_name[df$ccode == 368] <- "Northern Europe"
df$subregion_name[df$ccode == 212] <- "Western Europe"
df$subregion_name[df$ccode == 580] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 553] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 820] <- "South-eastern Asia"
df$subregion_name[df$ccode == 781] <- "Southern Asia"
df$subregion_name[df$ccode == 432] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 338] <- "Southern Europe"
df$subregion_name[df$ccode == 983] <- "Micronesia"
df$subregion_name[df$ccode == 435] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 590] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 70] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 987] <- "Micronesia"
df$subregion_name[df$ccode == 359] <- "Eastern Europe"
df$subregion_name[df$ccode == 221] <- "Western Europe"
df$subregion_name[df$ccode == 712] <- "Eastern Asia"
df$subregion_name[df$ccode == 341] <- "Southern Europe"
df$subregion_name[df$ccode == 600] <- "Northern Africa"
df$subregion_name[df$ccode == 541] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 775] <- "South-eastern Asia"
df$subregion_name[df$ccode == 565] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 970] <- "Micronesia"
df$subregion_name[df$ccode == 790] <- "Southern Asia"
df$subregion_name[df$ccode == 210] <- "Western Europe"
df$subregion_name[df$ccode == 920] <- "Australia and New Zealand"
df$subregion_name[df$ccode == 93] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 436] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 475] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 731] <- "Eastern Asia"
df$subregion_name[df$ccode == 385] <- "Northern Europe"
df$subregion_name[df$ccode == 698] <- "Western Asia"
df$subregion_name[df$ccode == 770] <- "Southern Asia"
df$subregion_name[df$ccode == 986] <- "Micronesia"
df$subregion_name[df$ccode == 95] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 910] <- "Melanesia"
df$subregion_name[df$ccode == 150] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 135] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 840] <- "South-eastern Asia"
df$subregion_name[df$ccode == 290] <- "Eastern Europe"
df$subregion_name[df$ccode == 235] <- "Southern Europe"
df$subregion_name[df$ccode == 694] <- "Western Asia"
df$subregion_name[df$ccode == 360] <- "Eastern Europe"
df$subregion_name[df$ccode == 365] <- "Eastern Europe"
df$subregion_name[df$ccode == 517] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 990] <- "Polynesia"
df$subregion_name[df$ccode == 331] <- "Southern Europe"
df$subregion_name[df$ccode == 403] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 670] <- "Western Asia"
df$subregion_name[df$ccode == 433] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 591] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 451] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 830] <- "South-eastern Asia"
df$subregion_name[df$ccode == 317] <- "Eastern Europe"
df$subregion_name[df$ccode == 349] <- "Southern Europe"
df$subregion_name[df$ccode == 940] <- "Melanesia"
df$subregion_name[df$ccode == 520] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 560] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 732] <- "Eastern Asia"
df$subregion_name[df$ccode == 626] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 230] <- "Southern Europe"
df$subregion_name[df$ccode == 780] <- "Southern Asia"
df$subregion_name[df$ccode == 625] <- "Northern Africa"
df$subregion_name[df$ccode == 115] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 572] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 380] <- "Northern Europe"
df$subregion_name[df$ccode == 225] <- "Western Europe"
df$subregion_name[df$ccode == 652] <- "Western Asia"
df$subregion_name[df$ccode == 713] <- "Eastern Asia"
df$subregion_name[df$ccode == 702] <- "Central Asia"
df$subregion_name[df$ccode == 510] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 800] <- "South-eastern Asia"
df$subregion_name[df$ccode == 860] <- "South-eastern Asia"
df$subregion_name[df$ccode == 461] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 955] <- "Polynesia"
df$subregion_name[df$ccode == 52] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 616] <- "Northern Africa"
df$subregion_name[df$ccode == 640] <- "Western Asia"
df$subregion_name[df$ccode == 701] <- "Central Asia"
df$subregion_name[df$ccode == 947] <- "Polynesia"
df$subregion_name[df$ccode == 500] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 369] <- "Eastern Europe"
df$subregion_name[df$ccode == 696] <- "Western Asia"
df$subregion_name[df$ccode == 200] <- "Northern Europe"
df$subregion_name[df$ccode == 2] <- "Northern America"
df$subregion_name[df$ccode == 165] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 704] <- "Central Asia"
df$subregion_name[df$ccode == 935] <- "Melanesia"
df$subregion_name[df$ccode == 101] <- "Latin  America and the Caribbean"
df$subregion_name[df$ccode == 816] <- "South-eastern Asia"
df$subregion_name[df$ccode == 679] <- "Western Asia"
df$subregion_name[df$ccode == 551] <- "Sub-Saharan Africa"
df$subregion_name[df$ccode == 552] <- "Sub-Saharan Africa"
