# Correlates of War country code to country name

df$country[df$ccode == 2] <- "United States of America"
df$country[df$ccode == 20] <- "Canada"
df$country[df$ccode == 31] <- "Bahamas"
df$country[df$ccode == 40] <- "Cuba"
df$country[df$ccode == 41] <- "Haiti"
df$country[df$ccode == 42] <- "Dominican Republic"
df$country[df$ccode == 51] <- "Jamaica"
df$country[df$ccode == 52] <- "Trinidad and Tobago"
df$country[df$ccode == 53] <- "Barbados"
df$country[df$ccode == 54] <- "Dominica"
df$country[df$ccode == 55] <- "Grenada"
df$country[df$ccode == 56] <- "St. Lucia"
df$country[df$ccode == 57] <- "St. Vincent and the Grenadines"
df$country[df$ccode == 58] <- "Antigua and Barbuda"
df$country[df$ccode == 60] <- "St. Kitts and Nevis"
df$country[df$ccode == 70] <- "Mexico"
df$country[df$ccode == 80] <- "Belize"
df$country[df$ccode == 90] <- "Guatemala"
df$country[df$ccode == 91] <- "Honduras"
df$country[df$ccode == 92] <- "El Salvador"
df$country[df$ccode == 93] <- "Nicaragua"
df$country[df$ccode == 94] <- "Costa Rica"
df$country[df$ccode == 95] <- "Panama"
df$country[df$ccode == 100] <- "Colombia"
df$country[df$ccode == 101] <- "Venezuela"
df$country[df$ccode == 110] <- "Guyana"
df$country[df$ccode == 115] <- "Suriname"
df$country[df$ccode == 130] <- "Ecuador"
df$country[df$ccode == 135] <- "Peru"
df$country[df$ccode == 140] <- "Brazil"
df$country[df$ccode == 145] <- "Bolivia"
df$country[df$ccode == 150] <- "Paraguay"
df$country[df$ccode == 155] <- "Chile"
df$country[df$ccode == 160] <- "Argentina"
df$country[df$ccode == 165] <- "Uruguay"
df$country[df$ccode == 200] <- "United Kingdom"
df$country[df$ccode == 205] <- "Ireland"
df$country[df$ccode == 210] <- "Netherlands"
df$country[df$ccode == 211] <- "Belgium"
df$country[df$ccode == 212] <- "Luxembourg"
df$country[df$ccode == 220] <- "France"
df$country[df$ccode == 221] <- "Monaco"
df$country[df$ccode == 223] <- "Liechtenstein"
df$country[df$ccode == 225] <- "Switzerland"
df$country[df$ccode == 230] <- "Spain"
df$country[df$ccode == 232] <- "Andorra"
df$country[df$ccode == 235] <- "Portugal"
df$country[df$ccode == 255] <- "Germany"
df$country[df$ccode == 260] <- "German Federal Republic"
df$country[df$ccode == 265] <- "German Democratic Republic"
df$country[df$ccode == 290] <- "Poland"
df$country[df$ccode == 305] <- "Austria"
df$country[df$ccode == 310] <- "Hungary"
df$country[df$ccode == 315] <- "Czechoslovakia"
df$country[df$ccode == 316] <- "Czech Republic"
df$country[df$ccode == 317] <- "Slovakia"
df$country[df$ccode == 325] <- "Italy"
df$country[df$ccode == 331] <- "San Marino"
df$country[df$ccode == 338] <- "Malta"
df$country[df$ccode == 339] <- "Albania"
df$country[df$ccode == 343] <- "Macedonia"
df$country[df$ccode == 344] <- "Croatia"
df$country[df$ccode == 345] <- "Yugoslavia"
df$country[df$ccode == 346] <- "Bosnia and Herzegovina"
df$country[df$ccode == 349] <- "Slovenia"
df$country[df$ccode == 350] <- "Greece"
df$country[df$ccode == 352] <- "Cyprus"
df$country[df$ccode == 355] <- "Bulgaria"
df$country[df$ccode == 359] <- "Moldova"
df$country[df$ccode == 360] <- "Romania"
df$country[df$ccode == 365] <- "Russia"
df$country[df$ccode == 366] <- "Estonia"
df$country[df$ccode == 367] <- "Latvia"
df$country[df$ccode == 368] <- "Lithuania"
df$country[df$ccode == 369] <- "Ukraine"
df$country[df$ccode == 370] <- "Belarus"
df$country[df$ccode == 371] <- "Armenia"
df$country[df$ccode == 372] <- "Georgia"
df$country[df$ccode == 373] <- "Azerbaijan"
df$country[df$ccode == 375] <- "Finland"
df$country[df$ccode == 380] <- "Sweden"
df$country[df$ccode == 385] <- "Norway"
df$country[df$ccode == 390] <- "Denmark"
df$country[df$ccode == 395] <- "Iceland"
df$country[df$ccode == 402] <- "Cape Verde"
df$country[df$ccode == 403] <- "Sao Tome and Principe"
df$country[df$ccode == 404] <- "Guinea-Bissau"
df$country[df$ccode == 411] <- "Equatorial Guinea"
df$country[df$ccode == 420] <- "Gambia"
df$country[df$ccode == 432] <- "Mali"
df$country[df$ccode == 433] <- "Senegal"
df$country[df$ccode == 434] <- "Benin"
df$country[df$ccode == 435] <- "Mauritania"
df$country[df$ccode == 436] <- "Niger"
df$country[df$ccode == 437] <- "Cote d'Ivoire"
df$country[df$ccode == 438] <- "Guinea"
df$country[df$ccode == 439] <- "Burkina Faso"
df$country[df$ccode == 450] <- "Liberia"
df$country[df$ccode == 451] <- "Sierra Leone"
df$country[df$ccode == 452] <- "Ghana"
df$country[df$ccode == 461] <- "Togo"
df$country[df$ccode == 471] <- "Cameroon"
df$country[df$ccode == 475] <- "Nigeria"
df$country[df$ccode == 481] <- "Gabon"
df$country[df$ccode == 482] <- "Central African Republic"
df$country[df$ccode == 483] <- "Chad"
df$country[df$ccode == 484] <- "Republic of the Congo"
df$country[df$ccode == 490] <- "Democratic Republic of the Congo"
df$country[df$ccode == 500] <- "Uganda"
df$country[df$ccode == 501] <- "Kenya"
df$country[df$ccode == 510] <- "Tanzania"
df$country[df$ccode == 511] <- "Zanzibar"
df$country[df$ccode == 516] <- "Burundi"
df$country[df$ccode == 517] <- "Rwanda"
df$country[df$ccode == 520] <- "Somalia"
df$country[df$ccode == 522] <- "Djibouti"
df$country[df$ccode == 530] <- "Ethiopia"
df$country[df$ccode == 531] <- "Eritrea"
df$country[df$ccode == 540] <- "Angola"
df$country[df$ccode == 541] <- "Mozambique"
df$country[df$ccode == 551] <- "Zambia"
df$country[df$ccode == 552] <- "Zimbabwe"
df$country[df$ccode == 553] <- "Malawi"
df$country[df$ccode == 560] <- "South Africa"
df$country[df$ccode == 565] <- "Namibia"
df$country[df$ccode == 570] <- "Lesotho"
df$country[df$ccode == 571] <- "Botswana"
df$country[df$ccode == 572] <- "Swaziland"
df$country[df$ccode == 580] <- "Madagascar"
df$country[df$ccode == 581] <- "Comoros"
df$country[df$ccode == 590] <- "Mauritius"
df$country[df$ccode == 591] <- "Seychelles"
df$country[df$ccode == 600] <- "Morocco"
df$country[df$ccode == 615] <- "Algeria"
df$country[df$ccode == 616] <- "Tunisia"
df$country[df$ccode == 620] <- "Libya"
df$country[df$ccode == 625] <- "Sudan"
df$country[df$ccode == 630] <- "Iran"
df$country[df$ccode == 640] <- "Turkey"
df$country[df$ccode == 645] <- "Iraq"
df$country[df$ccode == 651] <- "Egypt"
df$country[df$ccode == 652] <- "Syria"
df$country[df$ccode == 660] <- "Lebanon"
df$country[df$ccode == 663] <- "Jordan"
df$country[df$ccode == 666] <- "Israel"
df$country[df$ccode == 670] <- "Saudi Arabia"
df$country[df$ccode == 678] <- "Yemen Arab Republic"
df$country[df$ccode == 679] <- "Yemen"
df$country[df$ccode == 680] <- "Yemen People's Republic"
df$country[df$ccode == 690] <- "Kuwait"
df$country[df$ccode == 692] <- "Bahrain"
df$country[df$ccode == 694] <- "Qatar"
df$country[df$ccode == 696] <- "United Arab Emirates"
df$country[df$ccode == 698] <- "Oman"
df$country[df$ccode == 700] <- "Afghanistan"
df$country[df$ccode == 701] <- "Turkmenistan"
df$country[df$ccode == 702] <- "Tajikistan"
df$country[df$ccode == 703] <- "Kyrgyzstan"
df$country[df$ccode == 703] <- "Kyrgyz Republic"
df$country[df$ccode == 704] <- "Uzbekistan"
df$country[df$ccode == 705] <- "Kazakhstan"
df$country[df$ccode == 710] <- "China"
df$country[df$ccode == 712] <- "Mongolia"
df$country[df$ccode == 713] <- "Taiwan"
df$country[df$ccode == 730] <- "Korea"
df$country[df$ccode == 731] <- "North Korea"
df$country[df$ccode == 732] <- "South Korea"
df$country[df$ccode == 740] <- "Japan"
df$country[df$ccode == 750] <- "India"
df$country[df$ccode == 760] <- "Bhutan"
df$country[df$ccode == 770] <- "Pakistan"
df$country[df$ccode == 771] <- "Bangladesh"
df$country[df$ccode == 775] <- "Myanmar"
df$country[df$ccode == 780] <- "Sri Lanka"
df$country[df$ccode == 781] <- "Maldives"
df$country[df$ccode == 790] <- "Nepal"
df$country[df$ccode == 800] <- "Thailand"
df$country[df$ccode == 811] <- "Cambodia"
df$country[df$ccode == 812] <- "Laos"
df$country[df$ccode == 816] <- "Vietnam"
df$country[df$ccode == 817] <- "Republic of Vietnam"
df$country[df$ccode == 820] <- "Malaysia"
df$country[df$ccode == 830] <- "Singapore"
df$country[df$ccode == 835] <- "Brunei"
df$country[df$ccode == 840] <- "Philippines"
df$country[df$ccode == 850] <- "Indonesia"
df$country[df$ccode == 860] <- "East Timor"
df$country[df$ccode == 900] <- "Australia"
df$country[df$ccode == 910] <- "Papua New Guinea"
df$country[df$ccode == 920] <- "New Zealand"
df$country[df$ccode == 935] <- "Vanuatu"
df$country[df$ccode == 940] <- "Solomon Islands"
df$country[df$ccode == 946] <- "Kiribati"
df$country[df$ccode == 947] <- "Tuvalu"
df$country[df$ccode == 950] <- "Fiji"
df$country[df$ccode == 955] <- "Tonga"
df$country[df$ccode == 970] <- "Nauru"
df$country[df$ccode == 983] <- "Marshall Islands"
df$country[df$ccode == 986] <- "Palau"
df$country[df$ccode == 987] <- "Federated States of Micronesia"
df$country[df$ccode == 987] <- "Micronesia, Fed. Sts."
df$country[df$ccode == 990] <- "Samoa"
