# Gleditsch and Ward country number to country name

df$country[df$GWNo ==	2] <- "United States of America"
df$country[df$GWNo ==	20] <- "Canada"
df$country[df$GWNo ==	31] <- "Bahamas"
df$country[df$GWNo ==	40] <- "Cuba"
df$country[df$GWNo ==	41] <- "Haiti"
df$country[df$GWNo ==	42] <- "Dominican Republic"
df$country[df$GWNo ==	51] <- "Jamaica"
df$country[df$GWNo ==	52] <- "Trinidad and Tobago"
df$country[df$GWNo ==	53] <- "Barbados"
df$country[df$GWNo ==	54] <- "Dominica"
df$country[df$GWNo ==	55] <- "Grenada"
df$country[df$GWNo ==	56] <- "Saint Lucia"
df$country[df$GWNo ==	57] <- "St. Vincent and the Grenadines" 
df$country[df$GWNo ==	58] <- "Antigua and Barbuda"
df$country[df$GWNo ==	60] <- "St. Kitts and Nevis"
df$country[df$GWNo ==	70] <- "Mexico"
df$country[df$GWNo ==	80] <- "Belize"
df$country[df$GWNo ==	89] <- "UPC"
df$country[df$GWNo ==	90] <- "Guatemala"
df$country[df$GWNo ==	91] <- "Honduras"
df$country[df$GWNo ==	92] <- "El Salvador"
df$country[df$GWNo ==	93] <- "Nicaragua"
df$country[df$GWNo ==	94] <- "Costa Rica"
df$country[df$GWNo ==	95] <- "Panama"
df$country[df$GWNo ==	99] <- "Great Colombia"
df$country[df$GWNo ==	100] <- "Colombia"
df$country[df$GWNo ==	101] <- "Venezuela"
df$country[df$GWNo ==	110] <- "Guyana"
df$country[df$GWNo ==	115] <- "Suriname"
df$country[df$GWNo ==	130] <- "Ecuador"
df$country[df$GWNo ==	135] <- "Peru"
df$country[df$GWNo ==	140] <- "Brazil"
df$country[df$GWNo ==	145] <- "Bolivia"
df$country[df$GWNo ==	150] <- "Paraguay"
df$country[df$GWNo ==	155] <- "Chile"
df$country[df$GWNo ==	160] <- "Argentina"
df$country[df$GWNo ==	165] <- "Uruguay"
df$country[df$GWNo ==	200] <- "United Kingdom"
df$country[df$GWNo ==	205] <- "Ireland"
df$country[df$GWNo ==	210] <- "Netherlands"
df$country[df$GWNo ==	211] <- "Belgium"
df$country[df$GWNo ==	212] <- "Luxembourg"
df$country[df$GWNo ==	220] <- "France"
df$country[df$GWNo ==	221] <- "Monaco"
df$country[df$GWNo ==	223] <- "Liechtenstein"
df$country[df$GWNo ==	225] <- "Switzerland"
df$country[df$GWNo ==	230] <- "Spain"
df$country[df$GWNo ==	231] <- "Andorra"
df$country[df$GWNo ==	235] <- "Portugal"
df$country[df$GWNo ==	240] <- "Hanover"
df$country[df$GWNo ==	245] <- "Bavaria"
df$country[df$GWNo ==	255] <- "Prussia"
df$country[df$GWNo ==	260] <- "Germany"
df$country[df$GWNo ==	265] <- "German Democratic Republic"
df$country[df$GWNo ==	267] <- "Baden"
df$country[df$GWNo ==	269] <- "Saxony"
df$country[df$GWNo ==	271] <- "WÃ¼rttemberg"
df$country[df$GWNo ==	273] <- "Hesse-Kassel"
df$country[df$GWNo ==	275] <- "Hesse-Darmstadt"
df$country[df$GWNo ==	280] <- "Mecklenburg-Schwerin"
df$country[df$GWNo ==	290] <- "Poland"
df$country[df$GWNo ==	300] <- "Austria-Hungary"
df$country[df$GWNo ==	305] <- "Austria"
df$country[df$GWNo ==	310] <- "Hungary"
df$country[df$GWNo ==	315] <- "Czechoslovakia"
df$country[df$GWNo ==	316] <- "Czech Republic"
df$country[df$GWNo ==	317] <- "Slovakia"
df$country[df$GWNo ==	325] <- "Italy"
df$country[df$GWNo ==	327] <- "Papal States"
df$country[df$GWNo ==	329] <- "Two Sicilies"
df$country[df$GWNo ==	331] <- "San Marino"
df$country[df$GWNo ==	332] <- "Modena"
df$country[df$GWNo ==	335] <- "Parma"
df$country[df$GWNo ==	337] <- "Tuscany"
df$country[df$GWNo ==	338] <- "Malta"
df$country[df$GWNo ==	339] <- "Albania"
df$country[df$GWNo ==	341] <- "Montenegro"
df$country[df$GWNo ==	343] <- "North Macedonia"
df$country[df$GWNo ==	344] <- "Croatia"
df$country[df$GWNo ==	340] <- "Serbia"
df$country[df$GWNo ==	345] <- "Yugoslavia"
df$country[df$GWNo ==	346] <- "Bosnia and Herzegovina"
df$country[df$GWNo ==	347] <- "Kosovo"
df$country[df$GWNo ==	349] <- "Slovenia"
df$country[df$GWNo ==	350] <- "Greece"
df$country[df$GWNo ==	352] <- "Cyprus"
df$country[df$GWNo ==	355] <- "Bulgaria"
df$country[df$GWNo ==	359] <- "Moldova"
df$country[df$GWNo ==	360] <- "Rumania"
df$country[df$GWNo ==	365] <- "Russia"
df$country[df$GWNo ==	366] <- "Estonia"
df$country[df$GWNo ==	367] <- "Latvia"
df$country[df$GWNo ==	368] <- "Lithuania"
df$country[df$GWNo ==	369] <- "Ukraine"
df$country[df$GWNo ==	370] <- "Belarus"
df$country[df$GWNo ==	371] <- "Armenia"
df$country[df$GWNo ==	372] <- "Georgia"
df$country[df$GWNo ==	373] <- "Azerbaijan"
df$country[df$GWNo ==	375] <- "Finland"
df$country[df$GWNo ==	380] <- "Sweden"
df$country[df$GWNo ==	385] <- "Norway"
df$country[df$GWNo ==	390] <- "Denmark"
df$country[df$GWNo ==	395] <- "Iceland"
df$country[df$GWNo ==	402] <- "Cabo Verde"
df$country[df$GWNo ==	403] <- "Sao Tome and Principe"
df$country[df$GWNo ==	404] <- "Guinea-Bissau"
df$country[df$GWNo ==	411] <- "Equatorial Guinea"
df$country[df$GWNo ==	420] <- "Gambia"
df$country[df$GWNo ==	432] <- "Mali"
df$country[df$GWNo ==	433] <- "Senegal"
df$country[df$GWNo ==	434] <- "Benin"
df$country[df$GWNo ==	435] <- "Mauritania"
df$country[df$GWNo ==	436] <- "Niger"
df$country[df$GWNo ==	437] <- "Cote d'Ivoire"
df$country[df$GWNo ==	438] <- "Guinea"
df$country[df$GWNo ==	439] <- "Burkina Faso"
df$country[df$GWNo ==	450] <- "Liberia"
df$country[df$GWNo ==	451] <- "Sierra Leone"
df$country[df$GWNo ==	452] <- "Ghana"
df$country[df$GWNo ==	461] <- "Togo"
df$country[df$GWNo ==	471] <- "Cameroon"
df$country[df$GWNo ==	475] <- "Nigeria"
df$country[df$GWNo ==	481] <- "Gabon"
df$country[df$GWNo ==	482] <- "Central African Republic"
df$country[df$GWNo ==	483] <- "Chad"
df$country[df$GWNo ==	484] <- "Republic of the Congo"
df$country[df$GWNo ==	490] <- "Democratic Republic of the Congo,"
df$country[df$GWNo ==	500] <- "Uganda"
df$country[df$GWNo ==	501] <- "Kenya"
df$country[df$GWNo ==	510] <- "Tanzania"
df$country[df$GWNo ==	511] <- "Zanzibar"
df$country[df$GWNo ==	516] <- "Burundi"
df$country[df$GWNo ==	517] <- "Rwanda"
df$country[df$GWNo ==	520] <- "Somalia"
df$country[df$GWNo ==	522] <- "Djibouti"
df$country[df$GWNo ==	530] <- "Ethiopia"
df$country[df$GWNo ==	531] <- "Eritrea"
df$country[df$GWNo ==	540] <- "Angola"
df$country[df$GWNo ==	541] <- "Mozambique"
df$country[df$GWNo ==	551] <- "Zambia"
df$country[df$GWNo ==	552] <- "Zimbabwe"
df$country[df$GWNo ==	553] <- "Malawi"
df$country[df$GWNo ==	560] <- "South Africa"
df$country[df$GWNo ==	563] <- "Transvaal"
df$country[df$GWNo ==	564] <- "Orange Free State"
df$country[df$GWNo ==	565] <- "Namibia"
df$country[df$GWNo ==	570] <- "Lesotho"
df$country[df$GWNo ==	571] <- "Botswana"
df$country[df$GWNo ==	572] <- "Eswatini"
df$country[df$GWNo ==	580] <- "Madagascar"
df$country[df$GWNo ==	581] <- "Comoros"
df$country[df$GWNo ==	590] <- "Mauritius"
df$country[df$GWNo ==	591] <- "Seychelles"
df$country[df$GWNo ==	600] <- "Morocco"
df$country[df$GWNo ==	615] <- "Algeria"
df$country[df$GWNo ==	616] <- "Tunisia"
df$country[df$GWNo ==	620] <- "Libya"
df$country[df$GWNo ==	625] <- "Sudan"
df$country[df$GWNo ==	626] <- "South Sudan"
df$country[df$GWNo ==	630] <- "Iran"
df$country[df$GWNo ==	640] <- "Turkey"
df$country[df$GWNo ==	645] <- "Iraq"
df$country[df$GWNo ==	651] <- "Egypt"
df$country[df$GWNo ==	652] <- "Syria"
df$country[df$GWNo ==	660] <- "Lebanon"
df$country[df$GWNo ==	663] <- "Jordan"
df$country[df$GWNo ==	666] <- "Israel"
df$country[df$GWNo ==	670] <- "Saudi Arabia"
df$country[df$GWNo ==	678] <- "Yemen"
df$country[df$GWNo ==	680] <- "Yemen, People's Republic of"
df$country[df$GWNo ==	690] <- "Kuwait"
df$country[df$GWNo ==	692] <- "Bahrain"
df$country[df$GWNo ==	694] <- "Qatar"
df$country[df$GWNo ==	696] <- "United Arab Emirates"
df$country[df$GWNo ==	698] <- "Oman"
df$country[df$GWNo ==	700] <- "Afghanistan"
df$country[df$GWNo ==	701] <- "Turkmenistan"
df$country[df$GWNo ==	702] <- "Tajikistan"
df$country[df$GWNo ==	703] <- "Kyrgyzstan"
df$country[df$GWNo ==	704] <- "Uzbekistan"
df$country[df$GWNo ==	705] <- "Kazakhstan"
df$country[df$GWNo ==	710] <- "China"
df$country[df$GWNo ==	711] <- "Tibet"
df$country[df$GWNo ==	712] <- "Mongolia"
df$country[df$GWNo ==	713] <- "Taiwan"
df$country[df$GWNo ==	732] <- "South Korea"
df$country[df$GWNo ==	731] <- "North Korea"
df$country[df$GWNo ==	740] <- "Japan"
df$country[df$GWNo ==	750] <- "India"
df$country[df$GWNo ==	760] <- "Bhutan"
df$country[df$GWNo ==	770] <- "Pakistan"
df$country[df$GWNo ==	771] <- "Bangladesh"
df$country[df$GWNo ==	775] <- "Myanmar"
df$country[df$GWNo ==	780] <- "Sri Lanka"
df$country[df$GWNo ==	781] <- "Maldives"
df$country[df$GWNo ==	790] <- "Nepal"
df$country[df$GWNo ==	800] <- "Thailand"
df$country[df$GWNo ==	811] <- "Cambodia"
df$country[df$GWNo ==	812] <- "Laos"
df$country[df$GWNo ==	815] <- "Vietnam (Tonkin)"
df$country[df$GWNo ==	816] <- "Vietnam, Democratic Republic of"
df$country[df$GWNo ==	817] <- "Vietnam, Republic of"
df$country[df$GWNo ==	820] <- "Malaysia"
df$country[df$GWNo ==	830] <- "Singapore"
df$country[df$GWNo ==	835] <- "Brunei"
df$country[df$GWNo ==	840] <- "Philippines"
df$country[df$GWNo ==	850] <- "Indonesia"
df$country[df$GWNo ==	860] <- "Timor-Leste"
df$country[df$GWNo ==	900] <- "Australia"
df$country[df$GWNo ==	910] <- "Papua New Guinea"
df$country[df$GWNo ==	920] <- "New Zealand"
df$country[df$GWNo ==	935] <- "Vanuatu"
df$country[df$GWNo ==	940] <- "Solomon Islands"
df$country[df$GWNo ==	950] <- "Fiji"
df$country[df$GWNo ==	970] <- "Kiribati"
df$country[df$GWNo ==	971] <- "Nauru"
df$country[df$GWNo ==	972] <- "Tonga"
df$country[df$GWNo ==	973] <- "Tuvalu"
df$country[df$GWNo ==	983] <- "Marshall Islands"
df$country[df$GWNo ==	986] <- "Palau"
df$country[df$GWNo ==	987] <- "Micronesia, Federated States of"
df$country[df$GWNo ==	990] <- "Samoa"

